// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// EXTRA TOOLS (Free APIs, Pure JS)
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

const axios = require("axios");
const config = require("../config/config");

module.exports = [
    { name: "weather", async execute(sock, from, args) { if (!args.length) return sock.sendMessage(from, { text: "❌ .weather <city>\nExample: .weather Nairobi" }); try { const res = await fetch(`https://wttr.in/${encodeURIComponent(args.join(" "))}?format=3`); if (!res.ok) throw new Error("HTTP " + res.status); const text = await res.text(); await sock.sendMessage(from, { text: "🌦️ " + text.trim() }); } catch (e) { await sock.sendMessage(from, { text: "❌ Weather lookup failed: " + e.message }); } } },
    { name: "define", aliases: ["urban"], async execute(sock, from, args) { if (!args.length) return sock.sendMessage(from, { text: "❌ .define <word>" }); try { const term = args.join(" "); const res = await fetch(`https://api.urbandictionary.com/v0/define?term=${encodeURIComponent(term)}`); const data = await res.json(); if (!data.list || !data.list.length) return sock.sendMessage(from, { text: "❌ No definition found." }); const d = data.list[0]; const def = d.definition.replace(/[\[\]]/g, "").slice(0, 600); const example = (d.example || "").replace(/[\[\]]/g, "").slice(0, 300); await sock.sendMessage(from, { text: `📖 *${term}*\n\n${def}${example ? `\n\n_Example:_ ${example}` : ""}` }); } catch (e) { await sock.sendMessage(from, { text: "❌ Define failed: " + e.message }); } } },
    { name: "lyrics", async execute(sock, from, args) { if (!args.length) return sock.sendMessage(from, { text: "❌ .lyrics <artist> - <song>\nExample: .lyrics Adele - Hello" }); const parts = args.join(" ").split(" - "); if (parts.length < 2) return sock.sendMessage(from, { text: "❌ Format: .lyrics <artist> - <song>" }); const [artist, song] = parts; try { const res = await fetch(`https://api.lyrics.ovh/v1/${encodeURIComponent(artist.trim())}/${encodeURIComponent(song.trim())}`); const data = await res.json(); if (!data.lyrics) return sock.sendMessage(from, { text: "❌ Lyrics not found." }); const trimmed = data.lyrics.length > 3500 ? data.lyrics.slice(0, 3500) + "\n\n... (truncated)" : data.lyrics; await sock.sendMessage(from, { text: `🎵 *${song.trim()}* — ${artist.trim()}\n\n${trimmed}` }); } catch (e) { await sock.sendMessage(from, { text: "❌ Lyrics lookup failed: " + e.message }); } } },
    { name: "wordcount", async execute(sock, from, args) { if (!args.length) return sock.sendMessage(from, { text: "❌ .wordcount text" }); const text = args.join(" "); await sock.sendMessage(from, { text: `📊 Words: ${text.split(/\s+/).filter(Boolean).length}\nCharacters: ${text.length}` }); } },
    { name: "palindrome", async execute(sock, from, args) { if (!args.length) return sock.sendMessage(from, { text: "❌ .palindrome text" }); const clean = args.join("").toLowerCase().replace(/[^a-z0-9]/g, ""); const isPal = clean === clean.split("").reverse().join(""); await sock.sendMessage(from, { text: isPal ? "✅ That's a palindrome!" : "❌ Not a palindrome." }); } },
    { name: "password", aliases: ["genpass"], async execute(sock, from, args) { const len = Math.min(Math.max(parseInt(args[0], 10) || 12, 6), 64); const chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*"; let out = ""; for (let i = 0; i < len; i++) out += chars[Math.floor(Math.random() * chars.length)]; await sock.sendMessage(from, { text: "🔐 " + out }); } },
    { name: "gitclone", aliases: ["clone"], async execute(sock, from, args) { if (!args.length) return sock.sendMessage(from, { text: "❌ .gitclone <owner/repo or full GitHub URL>\nExample: .gitclone Karl-tech665/PRIMACY-SPX-ULTRA" }); const input = args[0]; const m = input.match(/github\.com\/([^\/]+)\/([^\/\s]+)/i); let owner, repo; if (m) { owner = m[1]; repo = m[2].replace(/\.git$/, ""); } else { const parts = input.split("/"); if (parts.length === 2) { owner = parts[0]; repo = parts[1]; } } if (!owner || !repo) return sock.sendMessage(from, { text: "❌ Couldn't parse that as a GitHub repo." }); try { const zipUrl = `https://github.com/${owner}/${repo}/archive/refs/heads/main.zip`; await sock.sendMessage(from, { document: { url: zipUrl }, mimetype: "application/zip", fileName: `${repo}.zip`, caption: `📦 ${owner}/${repo}` }); } catch (e) { await sock.sendMessage(from, { text: "❌ Failed to fetch repo: " + e.message }); } } }
];
