// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// MEDIA COMMANDS (Real Downloading)
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

const axios = require("axios");
const config = require("../config/config");

module.exports = [
    { name: "tiktok", async execute(sock, from, args) { if (!args.length) return sock.sendMessage(from, { text: "❌ .tiktok URL" }); try { const { tiktok } = require("@bochilteam/scraper"); const r = await tiktok(args[0]); const v = r.video || r.nowm || r.video_with_watermark; if (v) await sock.sendMessage(from, { video: { url: v }, caption: "📱 TikTok" }); else await sock.sendMessage(from, { text: "❌ Failed" }); } catch (e) { await sock.sendMessage(from, { text: "❌ " + e.message }); } } },
    { name: "instagram", aliases: ["ig"], async execute(sock, from, args) { if (!args.length) return sock.sendMessage(from, { text: "❌ .ig URL" }); try { const { instagram } = require("@bochilteam/scraper"); const r = await instagram(args[0]); const m = r.media || r.video; if (m) { const isV = m.includes(".mp4"); await sock.sendMessage(from, { [isV ? "video" : "image"]: { url: m }, caption: "📸 Instagram" }); } else await sock.sendMessage(from, { text: "❌ Failed" }); } catch (e) { await sock.sendMessage(from, { text: "❌ " + e.message }); } } },
    { name: "facebook", aliases: ["fb"], async execute(sock, from, args) { if (!args.length) return sock.sendMessage(from, { text: "❌ .fb URL" }); try { const { facebook } = require("@bochilteam/scraper"); const r = await facebook(args[0]); const v = r.hd || r.sd; if (v) await sock.sendMessage(from, { video: { url: v }, caption: "📘 Facebook" }); else await sock.sendMessage(from, { text: "❌ Failed" }); } catch (e) { await sock.sendMessage(from, { text: "❌ " + e.message }); } } },
    { name: "twitter", async execute(sock, from, args) { if (!args.length) return sock.sendMessage(from, { text: "❌ .twitter URL" }); try { const { twitter } = require("@bochilteam/scraper"); const r = await twitter(args[0]); const v = r.hd || r.sd; if (v) await sock.sendMessage(from, { video: { url: v }, caption: "🐦 Twitter" }); else await sock.sendMessage(from, { text: "❌ Failed" }); } catch (e) { await sock.sendMessage(from, { text: "❌ " + e.message }); } } },
    { name: "ytaudio", async execute(sock, from, args) { if (!args.length) return sock.sendMessage(from, { text: "❌ .ytaudio query" }); try { const ytSearch = require("yt-search"); const ytdl = require("ytdl-core"); const s = await ytSearch(args.join(" ")); if (!s.videos.length) return sock.sendMessage(from, { text: "❌ No results." }); const v = s.videos[0]; const stream = ytdl(v.url, { filter: "audioonly", quality: "lowest" }); await sock.sendMessage(from, { audio: stream, mimetype: "audio/mpeg", fileName: v.title + ".mp3", caption: "🎵 " + v.title }); } catch (e) { await sock.sendMessage(from, { text: "❌ " + e.message }); } } },
    { name: "ytvideo", async execute(sock, from, args) { if (!args.length) return sock.sendMessage(from, { text: "❌ .ytvideo query" }); try { const ytSearch = require("yt-search"); const ytdl = require("ytdl-core"); const s = await ytSearch(args.join(" ")); if (!s.videos.length) return sock.sendMessage(from, { text: "❌ No results." }); const v = s.videos[0]; const stream = ytdl(v.url, { quality: "lowest", filter: "audioandvideo" }); await sock.sendMessage(from, { video: stream, caption: "🎬 " + v.title }); } catch (e) { await sock.sendMessage(from, { text: "❌ " + e.message }); } } },
    { name: "play", async execute(sock, from, args, msg, extra = {}) { const y = (extra.commands || {}).ytaudio; if (y) return y.execute(sock, from, args, msg, extra); await sock.sendMessage(from, { text: "❌ ytaudio unavailable." }); } }
];
